import Link from "next/link";
import { ArrowLeft, Info } from "@phosphor-icons/react";
import type { LearnerExercise } from "../types/learner-exercises.types";
import { formatExerciseDate, getExerciseSessionHref } from "../utils/learner-exercises.utils";
import { ExerciseBadges } from "./ExerciseBadges";

export function ExerciseWorkspaceHeader({ exercise, helperText }: { exercise: LearnerExercise; helperText: string }) {
  return <header className="relative flex h-16 shrink-0 items-center gap-3 rounded-2xl border border-border bg-white px-3 shadow-sm sm:px-4"><Link href={getExerciseSessionHref(exercise)} className="inline-flex size-10 shrink-0 items-center justify-center rounded-xl text-[#280F91] hover:bg-[#EEF2FF]" aria-label="Quay lại bài tập của buổi học"><ArrowLeft size={19} weight="bold" /></Link><div className="min-w-0 flex-1"><h1 className="truncate text-sm font-extrabold text-slate-950 sm:text-base">{exercise.title}</h1><p className="mt-0.5 truncate text-xs font-semibold text-slate-500">{exercise.className} | {exercise.lessonTopic}</p></div><div className="hidden shrink-0 lg:block"><ExerciseBadges source={exercise.source} status={exercise.status} difficulty={exercise.difficulty} /></div><details className="group relative shrink-0 [&>summary::-webkit-details-marker]:hidden"><summary className="grid size-10 cursor-pointer list-none place-items-center rounded-xl border border-border text-slate-600 hover:bg-slate-50 hover:text-[#280F91]" aria-label="Xem thông tin bài tập"><Info size={19} weight="bold" /></summary><div className="absolute right-0 top-12 z-20 w-[min(340px,calc(100vw-2rem))] rounded-2xl border border-border bg-white p-4 shadow-xl shadow-[#280F91]/10"><ExerciseBadges source={exercise.source} status={exercise.status} difficulty={exercise.difficulty} /><h2 className="mt-3 text-sm font-extrabold text-slate-950">Thông tin bài tập</h2><p className="mt-1.5 text-sm leading-6 text-slate-600">{exercise.description}</p><dl className="mt-3 grid gap-2 text-xs"><div><dt className="text-slate-500">Gia sư</dt><dd className="mt-0.5 font-bold text-slate-800">{exercise.tutorName}</dd></div><div><dt className="text-slate-500">Hạn hoàn thành</dt><dd className="mt-0.5 font-bold text-slate-800">{formatExerciseDate(exercise.dueAt)}</dd></div><div><dt className="text-slate-500">Thời gian dự kiến</dt><dd className="mt-0.5 font-bold text-slate-800">{exercise.estimatedMinutes} phút</dd></div></dl><p className="mt-3 rounded-xl bg-[#FFF9E8] px-3 py-2.5 text-xs font-semibold leading-5 text-[#6D4A13]">{helperText}</p></div></details></header>;
}
