import { CommunityPost, UserProfile } from "../types/community";

export const mockGuest: UserProfile = {
  id: "guest-1",
  email: null,
  firstName: "Khách",
  lastName: "Vô danh",
  fullName: "Khách",
  phoneNumber: null,
  role: "GUEST",
  status: "ACTIVE",
  permissions: [],
  displayName: "Khách",
};

export const mockLearnerNoSession: UserProfile = {
  id: "learner-1",
  email: "learner1@example.com",
  firstName: "Nguyễn",
  lastName: "An",
  fullName: "Nguyễn An",
  phoneNumber: "0901234567",
  role: "LEARNER",
  status: "ACTIVE",
  permissions: ["CREATE_POST"],
  hasActiveLearnerClass: false,
  displayName: "Nguyễn An",
  avatarUrl: "https://i.pravatar.cc/150?u=learner-1",
};

export const mockLearnerWithActiveSession: UserProfile = {
  id: "learner-2",
  email: "learner2@example.com",
  firstName: "Trần",
  lastName: "Bình",
  fullName: "Trần Bình",
  phoneNumber: "0912345678",
  role: "LEARNER",
  status: "ACTIVE",
  permissions: ["CREATE_POST"],
  hasActiveLearnerClass: true, // This maps to "active session" for our mock
  displayName: "Trần Bình",
  avatarUrl: "https://i.pravatar.cc/150?u=learner-2",
};

export const mockTutor: UserProfile = {
  id: "tutor-1",
  email: "tutor1@example.com",
  firstName: "Lê",
  lastName: "Cường",
  fullName: "Lê Cường",
  phoneNumber: "0923456789",
  role: "TUTOR",
  status: "ACTIVE",
  permissions: ["APPLY_POST"],
  tutorProfileId: "tutor-profile-1",
  displayName: "Gia sư Lê Cường",
  avatarUrl: "https://i.pravatar.cc/150?u=tutor-1",
};

export const mockTutor2: UserProfile = {
  id: "tutor-2",
  email: "tutor2@example.com",
  firstName: "Phạm",
  lastName: "Dung",
  fullName: "Phạm Dung",
  phoneNumber: "0934567890",
  role: "TUTOR",
  status: "ACTIVE",
  permissions: ["APPLY_POST"],
  tutorProfileId: "tutor-profile-2",
  displayName: "Gia sư Phạm Dung",
  avatarUrl: "https://i.pravatar.cc/150?u=tutor-2",
};

export const initialMockPosts: CommunityPost[] = [
  {
    id: "post-1",
    author: mockLearnerNoSession,
    content: "Mình cần tìm gia sư môn Toán lớp 12 luyện thi đại học, ưu tiên các bạn có kinh nghiệm luyện thi khối A. Khu vực Quận 10.",
    imageUrls: [],
    subject: "Toán",
    gradeLevel: "12",
    teachingMode: "OFFLINE",
    city: "Hồ Chí Minh",
    district: "Quận 10",
    budgetPerSession: 250000,
    status: "OPEN",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
    applicationsCount: 3,
    applications: [
      {
        id: "app-1",
        postId: "post-1",
        tutor: mockTutor,
        pitchNote: "Chào bạn, mình có 3 năm kinh nghiệm luyện thi đại học khối A, điểm số học sinh trung bình 8+.",
        proposedRate: 250000,
        availableSlots: ["Thứ 2,4,6 tối"],
        createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        status: "PENDING",
      }
    ],
  },
  {
    id: "post-2",
    author: mockLearnerWithActiveSession,
    content: "Cần tìm giáo viên dạy tiếng Anh giao tiếp cho bé lớp 5. Học online qua Zoom, cần kiên nhẫn, vui vẻ.",
    imageUrls: ["https://placehold.co/600x400/png?text=English+Class"],
    subject: "Tiếng Anh",
    gradeLevel: "5",
    teachingMode: "ONLINE",
    budgetPerSession: 200000,
    status: "OPEN",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    applicationsCount: 5,
    applications: [],
  },
  {
    id: "post-3",
    author: { ...mockLearnerNoSession, id: "learner-3", displayName: "Phụ huynh bé Hoa" },
    content: "Tìm gia sư Hóa học 9 ôn thi vào lớp 10 chuyên Hóa. Yêu cầu sinh viên Sư Phạm Hóa hoặc KHTN. Dạy tại Cầu Giấy.",
    imageUrls: [],
    subject: "Hóa học",
    gradeLevel: "9",
    teachingMode: "OFFLINE",
    city: "Hà Nội",
    district: "Quận Cầu Giấy",
    budgetPerSession: 300000,
    status: "IN_SESSION",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    applicationsCount: 1,
    applications: [
      {
        id: "app-2",
        postId: "post-3",
        tutor: mockTutor2,
        pitchNote: "Đã đạt giải QG Hóa, thủ khoa đầu vào SP Hóa.",
        proposedRate: 300000,
        availableSlots: ["Thứ 7, CN"],
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
        status: "ACCEPTED",
      }
    ],
  },
  {
    id: "post-4",
    author: { ...mockLearnerNoSession, id: "learner-4", displayName: "Hoàng Minh" },
    content: "Mình cần người hướng dẫn IELTS Speaking & Writing mục tiêu 6.5. Đã thi được 5.5 cách đây 1 năm.",
    imageUrls: [],
    subject: "IELTS",
    gradeLevel: "Khác",
    teachingMode: "ONLINE",
    budgetPerSession: 300000,
    status: "OPEN",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    applicationsCount: 0,
    applications: [],
  },
  {
    id: "post-5",
    author: { ...mockLearnerNoSession, id: "learner-5", displayName: "Trương Vô Kỵ" },
    content: "Bé nhà mình bị mất gốc Vật lý 10, cần gia sư đến kèm tại nhà để củng cố kiến thức trên lớp. Nhà ở Hải Châu.",
    imageUrls: [],
    subject: "Vật lý",
    gradeLevel: "10",
    teachingMode: "OFFLINE",
    city: "Đà Nẵng",
    district: "Quận Hải Châu",
    budgetPerSession: 180000,
    status: "OPEN",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    applicationsCount: 0,
    applications: [],
  },
  {
    id: "post-6",
    author: { ...mockLearnerNoSession, id: "learner-6", displayName: "Ngô Quyền" },
    content: "Tìm sinh viên Sư phạm Văn dạy kèm cho em gái lớp 8 môn Ngữ Văn.",
    imageUrls: [],
    subject: "Ngữ Văn",
    gradeLevel: "8",
    teachingMode: "HYBRID",
    city: "Hồ Chí Minh",
    district: "Quận Gò Vấp",
    budgetPerSession: 220000,
    status: "CLOSED",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    applicationsCount: 2,
    applications: [],
  }
];
